import './globals.css'
import { Inter, Lato } from 'next/font/google'
import TopBar from '@/components/TopBar/TopBar'


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

const lato = Lato({
  weight : ['100','300','400','700','900'],
  subsets : ['latin']
})



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body className={lato.className}>
        <TopBar/>
        {children}
        </body>
      </html>
  )
}
