import './globals.css'
import { Inter, Lato } from 'next/font/google'
import TopBar from '@/components/TopBar/TopBar'
import Footer from '@/components/Footer/Footer'
import StoreInfoType from '@/lib/Types/StoreInfoType'

const storeInfo : StoreInfoType = {
    name : "Hypespace",
    address: "ul. Krucza 12",
    address2: "04-697 Warszawa",
    openingHours : {
      mondayToFriday : "Pon. - Pt.: 9:00 - 20:00",
      saturday : "Sob.: 9:00 - 18:00",
      sunday : "Ndz.: 9:00 - 16:00"
    }
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

const lato = Lato({
  weight : ['100','300','400','700','900'],
  subsets : ['latin']
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body className={lato.className}>
        <TopBar/>
        {children}
        <Footer
          {...storeInfo}
        />
        </body>
      </html>
  )
}
